name: Create Google Service JSON

on:
  # Enables this workflow to be called from other workflows
  workflow_call:

jobs:
  create-service-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Google Service JSON
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' > \
          ${{ github.workspace }}/app/google-services.json | base64

      - name: Check Google Service JSON file is created
        run: |
          if [ -f ./app/google-services.json ]; then
          echo "google-services.json exists."
          else
          echo "google-services.json does not exist." >&2
          exit 1
          fi
        continue-on-error: false

      - name: Upload to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: google_service_json
          path: ${{ github.workspace }}/app/google-services.json

